export const ADD_NEW_ANNOUNCE = 'ADD_NEW_ANNOUNCE'
export const DELETE_ANNOUNCE = 'DELETE_ANNOUNCE'
export const SHOW_CURRENRT_ANNOUNCE = 'SHOW_CURRENRT_ANNOUNCE'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'